### ISSUE TITLE
Allow opening an image from the trash

### ISSUE THREAD

**Issue by MateusRodCosta** [flathub/org.gnome.eog#14]
flatpak 1.7.2-1, xdg-desktop-portal-gtk 1.7.1-1, xdg-desktop-portal 1.7.2-1

OS: Arch Linux 64-bits

eog version 3.36.1

Steps to reproduce:

1) Delete an image
2) Open the trash
3) Try to open the image with the flatpak version of eog

Expected result:
You are able to see the image, pressing delete allows you to permanently delete the image

Actual results:

![Screenshot from 2020-04-12 20-00-53](https://user-images.githubusercontent.com/24463334/79081943-55b6d300-7cf8-11ea-8402-21c4c49d8e09.png)

**Comment by BigmenPixel0** [comment]
fixed.
