### ISSUE TITLE
Unable to open heif images

### ISSUE THREAD

**Issue by cwmke** [flathub/org.gnome.eog#17]
Not sure if this is a license issue but it would be nice to have heif images work with flatpak eog.

**Comment by TingPing** [comment]
Looks like it is possible but a few things need to be built.

- libheif: https://github.com/strukturag/libheif
  - libde265: https://github.com/strukturag/libde265
  - For AVIF (because why not): dav1d: https://www.videolan.org/projects/dav1d.html
