### ISSUE TITLE
Can't delete a photo

### ISSUE THREAD

**Issue by rejurime** [flathub/org.gnome.eog#6]
When I press delete or try to delete an image from contex menu the program give me an error.
"No se pudo acceder a la papelera" I have Ubuntu 18.04 in Spanish.

**Comment by jurf** [comment]
Can you replicate that with an English locale? You can do so by running `env LANG=C flatpak run org.gnome.eog`.

**Comment by barthalion** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/114

**Comment by rejurime** [comment]
Here is the message in English.
![captura de pantalla de 2018-07-21 01-13-59](https://user-images.githubusercontent.com/7131403/43032005-7cfc2990-8c83-11e8-834c-c026a8ad8b12.png)

**Comment by kovzol** [comment]
I have the same problem since today. eog-3.28.1, Ubuntu 18.04.1.

**Comment by TingPing** [comment]
You surely need an updated `xdg-desktop-portal` on 18.04.

**Comment by kovzol** [comment]
I don't have `xdg-desktop-portal` here installed. But I learned that the problem disappears when I work on local files. The  problem appeared on a remotely mounted filesystem, namely with curlftpfs. And this type of problem is present with some other applications as well (including LibreOffice) when curlftpfs is used.

**Comment by TingPing** [comment]
Well you really need the portals for most desktop integration anyway...

**Comment by TingPing** [comment]
Anyway I'll close this since everything should work as well as it can with up to date portals.
